@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "email": "thiago@gmail.com",
  "password": "123456",
  "name": "Thiago"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "thiago@gmail.com",
  "password": "123456",
}